services:
  order_sql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./order_sql/:/docker-entrypoint-initdb.d
    networks:
      - OrderNet

  order_svc:
    build: ./order_svc/
    image: py_order
    ports:
      - 5503:5500
    networks:
      - EoNet
      - OrderNet
    depends_on: 
      order_sql:
        condition: service_started

  order_cons:
    build: ./order_cons/
    image: py_order_cons
    networks:
      - EoNet
      - OrderNet
    depends_on: 
      order_sql:
        condition: service_started
        
networks:
  OrderNet:
    external:
      name: networks_OrderNet
  EoNet:
    external:
      name: networks_EoNet