services:
  client_sql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./client_sql/:/docker-entrypoint-initdb.d
    networks:
      - ClientNet
  client_svc:
    build: ./client_svc/
    image: py_client
    ports:
      - 5500:5500
    networks:
      - EoNet
      - ClientNet
    depends_on: 
      client_sql:
        condition: service_started

networks:
  ClientNet:
    external:
      name: networks_ClientNet
  EoNet:
    external:
      name: networks_EoNet