services:
  eo_mq:
    image: rabbitmq:management
    ports:
      - 8080:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=radmin
      - RABBITMQ_DEFAULT_PASS=rpass
    networks:
      - EoNet

networks:
  EoNet:
    external:
        name: networks_EoNet